name: PHP Composer

on:
  push:
    branches: [ "main-release" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: read secret 
      run: echo "my host secret ${{secrets.YOOSAI_HOST_URL}}"
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.YOOSAI_HOST_URL }}
        username: ${{ secrets.YOOSAI_USERNAME }}
        password: ${{ secrets.YOOSAI_PASSWORD }}
        port: 22
        script: |
          cd /var/www/yoosai-php-ntt
          git pull

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
